# all-steps: program

# array_sum.o: array_sum.S
#     gcc -c $<

# array_sum_speed.o: array_sum_speed.c
#     gcc -c $<

# program: array_sum_speed.o array_sum.o
#     ld -o $@ $^ -lc /usr/lib/x86_64-linux-gnu/crt1.o --dynamic-linker /lib64/ld-linux-x86-64.so.2


clear:
	rm -f *.o program *.out my_program